### ISSUE TITLE
2.2.1-SNAPSHOT

### ISSUE THREAD

**Issue by janmagnus** [christophd/citrus-tools#1]
Hi Christoph

while using 2.2.1-SNAPSHOT this message arise: 
[unknown-version]: Could not find artifact com.consol.citrus:citrus:pom:2.2.1-SNAPSHOT in consol-labs-snapshots (http://labs.consol.de/maven/snapshots-repository/)

which version should I use ?

Magnus

**Comment by christophd** [comment]
Please use 2.2 version in POM as value for the property "citrus.version". As an alternative you could clone the core project (https://github.com/christophd/citrus) and build locally, too. After that you will have 2.2.1-SNAPSHOT version in your local Maven repo available and the error message is fixed.
